---
title: 'Assignment #4'
author: "Chadwick Reed"
date: "10/7/2020"
output:
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    theme: "paper"
    code_folding: hide
    message: FALSE
    results: 'hide'
    warning: FALSE
    tidy: TRUE
    error: TRUE
    echo: FALSE
---


# Setup

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading Data

```{r load libraries, message=FALSE, results='hide', echo=FALSE}
library(osmdata)
library(opentripplanner)
library(tidyverse)
library(sf)
library(ggthemes)
library(ggspatial)
```

```{r, message=FALSE, results='hide', echo=FALSE}
CLT_colleges <- st_read(
  "https://opendata.arcgis.com/datasets/ff6f0e1376a64d2e9a554efbaa737e95_11.kml?outSR=%7B%22latestWkid%22%3A2264%2C%22wkid%22%3A102719%7D")
```

## Configuring OTP

```{r, message=FALSE, results='hide', echo=FALSE}
opq(bbox = 'Charlotte NC USA') %>%
  add_osm_feature(key = 'highway') %>%
  osmdata_xml(file = 'OTP/graphs/default/CLT_streets.osm')
```

```{r, message=FALSE, results='hide', echo=FALSE}
NC_state_plane <- "+proj=lcc +lat_1=34.33333333333334 +lat_2=36.16666666666666 +lat_0=33.75 +lon_0=-79 +x_0=609601.22 +y_0=0 +ellps=GRS80 +datum=NAD83 +units=m +no_defs"

CLT_street_features <- opq(bbox = 'Charlotte NC USA') %>%
  add_osm_feature(key = 'highway') %>%
  osmdata_sf()

CLT_streets <- CLT_street_features$osm_lines %>%
  st_transform(crs = NC_state_plane)
```

### Street Map: Charlotte, North Carolina

```{r, message=FALSE, results='hide', echo=FALSE}
ggplot(CLT_streets) +
  geom_sf() +
  theme_map()
```

```{r, message=FALSE, results='hide', echo=FALSE}
path_otp <- otp_dl_jar("OTP")
path_data <- file.path(getwd(), "OTP")
path_otp <- paste(path_data, "otp.jar",sep = "/")
```

```{r, message=FALSE, results='hide', echo=FALSE}
otp_build_graph(otp = path_otp, dir = path_data, memory =1024)
otp_setup(otp = path_otp, dir = path_data, memory =1024)
otpcon <- otp_connect()
```

## Creating Isochrones

```{r, message=FALSE, results='hide', echo=FALSE, warning=FALSE}
iso_5min_walk <- 
  otp_isochrone(otpcon = otpcon, fromPlace = CLT_colleges, 
                mode = "WALK", cutoffSec = 300) %>%
  st_transform(crs = NC_state_plane) %>%
  mutate(mode = "walk")

iso_5min_drive <- 
  otp_isochrone(otpcon = otpcon, fromPlace = CLT_colleges, 
                mode = "CAR", cutoffSec = 300) %>%
  st_transform(crs = NC_state_plane) %>%
  mutate(mode = "drive")

iso_5min_bike <-
  otp_isochrone(otpcon = otpcon, fromPlace = CLT_colleges,
                mode = "BICYCLE", cutoffSec = 300) %>%
  st_transform(crs = NC_state_plane) %>%
  mutate(mode = "bike")

iso_10min_walk <- 
  otp_isochrone(otpcon = otpcon, fromPlace = CLT_colleges, 
                mode = "WALK", cutoffSec = 600) %>%
  st_transform(crs = NC_state_plane) %>%
  mutate(mode = "walk")

iso_10min_drive <- 
  otp_isochrone(otpcon = otpcon, fromPlace = CLT_colleges, 
                mode = "CAR", cutoffSec = 600) %>%
  st_transform(crs = NC_state_plane) %>%
  mutate(mode = "drive")

iso_10min_bike <-
  otp_isochrone(otpcon = otpcon, fromPlace = CLT_colleges,
                mode = "BICYCLE", cutoffSec = 600) %>%
  st_transform(crs = NC_state_plane) %>%
  mutate(mode = "bike")


otp_stop()
```

## Grouping Isochrones

```{r, message=FALSE, results='hide', echo=FALSE}
iso5_all_modes <- rbind(iso_5min_drive, iso_5min_bike, iso_5min_walk)

iso5_bikewalk <- rbind(iso_5min_bike, iso_5min_walk)

iso10_all_modes <- rbind(iso_10min_drive, iso_10min_bike, iso_10min_walk)

iso10_bikewalk <- rbind(iso_10min_bike, iso_10min_walk)

```


# Plots

## Maps

### Five Minute Tri-Mode

```{r}
right_side <- st_bbox(iso5_all_modes)$xmax
left_side  <- st_bbox(iso5_all_modes)$xmin
top_side <- st_bbox(iso5_all_modes)$ymax
bottom_side <- st_bbox(iso5_all_modes)$ymin

ggplot(iso5_all_modes) +
  annotation_map_tile(zoomin = 0, type = "cartolight", progress = "none") +
  geom_sf(aes(fill = mode), alpha = 0.5) +
  geom_sf(data = CLT_colleges, size = 0.75) +
  coord_sf(xlim = c(left_side, right_side), 
           ylim = c(bottom_side, top_side), expand = FALSE) +
  scale_fill_viridis_d(option = "viridis", name = "Area that is reachable within 5 minutes",
                       labels = c("By bike", "By car", "By foot")) +
  theme_map() + 
  theme(legend.position = "bottom") +
  labs(caption = "Basemap Copyright OpenStreetMap contributors")
```


### Ten Minute Tri-Mode

```{r}
right_side <- st_bbox(iso10_all_modes)$xmax
left_side  <- st_bbox(iso10_all_modes)$xmin
top_side <- st_bbox(iso10_all_modes)$ymax
bottom_side <- st_bbox(iso10_all_modes)$ymin

ggplot(iso10_all_modes) +
  annotation_map_tile(zoomin = 0, type = "cartolight", progress = "none") +
  geom_sf(aes(fill = mode), alpha = 0.5) +
  geom_sf(data = CLT_colleges, size = 0.75) +
  coord_sf(xlim = c(left_side, right_side), 
           ylim = c(bottom_side, top_side), expand = FALSE) +
  scale_fill_viridis_d(option = "viridis", name = "Area that is reachable within 5 minutes",
                       labels = c("By bike", "By car", "By foot")) +
  theme_map() + 
  theme(legend.position = "bottom") +
  labs(caption = "Basemap Copyright OpenStreetMap contributors")
```

## Graphs

### Driving vs. Walking: Five Minutes

```{r, warning=FALSE}
iso_areas <- iso5_all_modes %>%
  mutate(area = st_area(iso5_all_modes)) %>%
  st_set_geometry(NULL) %>%
  pivot_wider(names_from = mode, values_from = area) 

ggplot(iso_areas, 
       aes(x = as.numeric(walk), y = as.numeric(drive))) +
  geom_point() +
  geom_smooth(method = "lm",
              color = "3",
              se = FALSE,
              fullrange = TRUE) +
  scale_x_continuous(name = 
            "Area within a five-minute walking distance\nof a college\n(square km)",
            breaks = breaks <- seq(10000, 190000, by = 20000),
            labels = breaks / 1000000) +
  scale_y_continuous(name = 
            "Area within a five-minute driving distance\nof a college\n(square km)",
            breaks = breaks <- seq(0, 2500000, by = 100000),
            labels = breaks / 1000000) +
  theme_dark()
```

### Driving vs. Walking: Ten Minutes

```{r, warning=FALSE}
iso_areas <- iso10_all_modes %>%
  mutate(area = st_area(iso10_all_modes)) %>%
  st_set_geometry(NULL) %>%
  pivot_wider(names_from = mode, values_from = area) 

ggplot(iso_areas, 
       aes(x = as.numeric(walk), y = as.numeric(drive))) +
  geom_point() +
  geom_smooth(method = "lm",
              color = "3",
              se = FALSE,
              fullrange = TRUE) +
  scale_x_continuous(name = 
            "Area within a five-minute walking distance\nof a college\n(square km)",
            breaks = breaks <- seq(0, 1000000, by = 100000),
            labels = prettyNum(breaks / 1000000, digits = 4)) +
  scale_y_continuous(name = 
            "Area within a five-minute driving distance\nof a college\n(square km)",
            breaks = breaks <- seq(0, 20000000, by = (2000000)),
            labels = prettyNum(breaks / 10000000, digits = 4)) +
  theme_dark()
```
