---
title: "Assignment 1"
author: "Chadwick Reed"
date: "9/12/2020"
output: html_document
---

```{r load libraries}
library(tidycensus)
library(tidyverse)
library(ggplot2)
library(extrafont)
```

Some light data-wrangling, courtesy of Dr. Voulgaris:
```{r}
vars <- c(tot_hh = "H001001",
         tot_rural_hh = "H002005",
         tot_rent_hh = "H004004",
         avg_hh_size = "H012001",
         tot_pop = "P003001",
         nh_white_pop = "P005003",
         nh_black_pop = "P005004",
         nh_asian_pop = "P005006",
         hispanic_pop = "P005010",
         med_age = "P013001")

NC_tracts <- get_decennial(geography = "tract", variables = vars,
                           state = "NC", county = "Mecklenburg",
                           output = "wide") %>%
  mutate(rural = (tot_rural_hh == tot_hh) ,
         pct_rental = tot_rent_hh / tot_hh,
         majority_race_eth = case_when(
           nh_white_pop / tot_pop > 0.5 ~ "nh_white",
           nh_black_pop / tot_pop > 0.5 ~ "nh_black",
           nh_asian_pop / tot_pop > 0.5 ~ "nh_asian",
           hispanic_pop / tot_pop > 0.5 ~ "hispanic",
           (nh_white_pop + nh_black_pop + nh_asian_pop + hispanic_pop) /
             tot_pop < 0.5 ~ "other",
           TRUE ~ "None")) %>%
  filter(tot_pop > 0, tot_hh > 0) %>%
  select(GEOID, rural, majority_race_eth, 
         pct_rental, avg_hh_size, tot_pop, med_age) 
```

### Figure 1: scatter plot with trend lines
```{r}
ggplot(NC_tracts,
       aes(x = pct_rental,
           y = med_age,
           color = majority_race_eth)) +
  geom_point(shape = 1, size = 2) + geom_smooth(method = lm, se=FALSE) + 
  scale_x_continuous(name = "Rental households (proportion of tract total)",
                     breaks = seq(0, 1, by = 0.25),
                     labels = paste(seq(0, 100, by = 25), "%", sep = "")) +
  scale_y_continuous(name = "Median age within tract",
                     breaks = seq(10, 80, by = 5), limits = c(15, 55)) +
  scale_color_discrete(name = "Majority race/ethnicity",
                       labels = c("Hispanic",
                                  "Non-Hispanic Asian",
                                  "Non-Hispanic white",
                                  "No majority")) +
  theme_minimal() +
  theme(text = element_text(family = "Consolas", size = 8.5))
```


### Figure 2: many-column histogram
```{r}
ggplot(NC_tracts, 
       aes(
           x = med_age)) +
         geom_bar()+
scale_y_continuous(name = "Count", breaks = seq(0, 10, by=1)) +
  scale_x_continuous(name = "Median age within tract",
                     breaks = seq(20, 50, by = 2)) +
  theme_test() +
  theme(text = element_text(family = "Calibri"))
```

### Figure 3: basic multicolor histogram
```{r}
ggplot(NC_tracts, 
       aes(majority_race_eth, tot_pop, fill = majority_race_eth)) +
         geom_bar(stat = "summary") +
  scale_x_discrete(name = "Majority race/ethnicity", labels = c("Hispanic",
                                  "Non-Hispanic Black",
                                  "Non-Hispanic white",
                                  "No majority")) + 
  scale_y_continuous(name = "Total population") + 
  labs(title="Average Tract Population by Majority Race") +
  theme(legend.position = "none", text = element_text(family = "Times New Roman"))
```

### Figure 4: box-and-line
```{r}
ggplot(NC_tracts, aes(pct_rental)) +
         geom_boxplot() +
  geom_freqpoly(binwidth=.01) + scale_y_continuous(name = "Count", breaks = seq(0,10, by=1)) + 
                  scale_x_continuous(name = "Rental households (proportion of tract total)", breaks = seq(0,1, by=.1), labels = paste(seq(0, 100, by = 10), "%", sep = ""))
```

### Figure 5: multicolor boxplots
```{r}
# Installing and loading the infamous Wes Anderson-themed color palettes. Inspired by Gianina!!
library(wesanderson)
```

```{r}
ggplot(NC_tracts, aes(y = med_age, fill = majority_race_eth, col = majority_race_eth)) +
         geom_boxplot() + scale_color_manual(values = wes_palette(n=4, name="GrandBudapest2")) + scale_fill_manual(values = wes_palette(n=4, name="GrandBudapest1"), 
(name = "Majority race/ethnicity"),
labels = c("Hispanic",
                                  "Non-Hispanic Black",
                                  "Non-Hispanic white",
                                  "No majority")) + scale_y_continuous(name = "Median age") + guides(color = FALSE) + theme(axis.text.x = element_blank(), text=element_text(family = "Corbel", size = 10), panel.grid = element_blank())
```

### Figure 6: basic scatter-line
```{r}
ggplot(NC_tracts, aes(y=tot_pop, x=avg_hh_size)) + 
geom_point() + geom_smooth(method=lm, se=FALSE) +
scale_x_continuous(name = "Average household size", limits = c(0, 5)) +
scale_y_continuous(name = "Total population", limits = c(0, 10000))
```

### Figure 7: basic pie + caption
```{r}
pie_chart <- ggplot(NC_tracts, aes(x = 1, fill = majority_race_eth)) +
  geom_bar(position = "fill") +
  coord_polar(theta = "y") +
  scale_y_continuous(name = "Number of tracts") +
  scale_fill_manual(values = wes_palette(n=4, name="Royal1"), name = "Majority race/ethnicity",
                       labels = c("Hispanic",
                                  "Non-Hispanic\nAsian",
                                  "Non-Hispanic\nwhite",
                                  "No majority")) +
  theme_void() +  labs(title="North Carolina Census Tracts by Majority Race/Ethnicity", caption = "Produced by Chadwick Reed")

pie_chart
```

### Figure 8: ggridge
```{r}
# Installing ridges package (made by Claus Wilke)
library(ggridges)
```

```{r}
ggplot(NC_tracts, aes(x = avg_hh_size, y = majority_race_eth)) +
  geom_density_ridges(scale = 4, alpha = .5, color = "Red") + theme_ridges() +
  scale_y_discrete(expand = c(0.01, 0), name = "Majority race/ethnicity",
                       labels = c("Hispanic",
                                  "Non-Hispanic Asian",
                                  "Non-Hispanic white",
                                  "No majority")) +
  scale_x_continuous(expand = c(0, 0), name = "Average household size")
```

### Figure 9: violins
```{r}
ggplot(NC_tracts, 
       aes(x = majority_race_eth,
           y = med_age,
           fill = majority_race_eth)) +
  geom_violin() +
  geom_point(position = "jitter",
             alpha = 0.5,
             size = 0.5) +
  scale_x_discrete(name = "Majority race/ethnicity",
                       labels = c("Hispanic*",
                                  "Non-Hispanic Asian",
                                  "Non-Hispanic white",
                                  "No majority")) +
  scale_y_continuous(name = "Median age within tract",
                     breaks = seq(10, 80, by = 10)) +
  theme(legend.position = "none") + 
  labs(caption = "*Insufficient number of majority-Hispanic tracts")


```

### Figure 10: swirly
```{r}
ggplot(NC_tracts, 
       aes(x = avg_hh_size,
           y = tot_pop)) +
  geom_point(alpha = 0.99, size = .25, col="blue") +
  stat_smooth(color = "Thistle", linetype = 2, size = 3) +
  scale_x_continuous(name = "Average household size",
                     labels = c("5 or 1", "1.5", "2", "2.5",
                                "3", "3.5", "4", "4.5", "5"),
                     breaks = seq(1, 5, by = 0.5)) +
  scale_y_continuous(name = "Tract population",
                     trans = "log",
                     breaks = c(10, 100, 1000, 10000),
                     labels = c("10", "100", "1,000", "10,000")) +
  coord_polar(theta = "x") +
  theme_bw() 
```

 
 